# Generated by Django 5.0.6 on 2024-05-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
